// <auto-generated />
using LVDDay9.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LVDDay9.Migrations
{
    [DbContext(typeof(LVDDay9Context))]
    partial class LVDDay9ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LVDDay9.Models.LvdLoai_San_Pham", b =>
                {
                    b.Property<long>("lvdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lvdId"));

                    b.Property<string>("lvdMaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("lvdTenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("lvdTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("lvdId");

                    b.HasIndex("lvdMaLoai")
                        .IsUnique();

                    b.ToTable("LvdLoai_San_Pham");
                });

            modelBuilder.Entity("LVDDay9.Models.LvdSan_Pham", b =>
                {
                    b.Property<long>("lvdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("lvdId"));

                    b.Property<decimal>("lvdDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("lvdHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("lvdLoaiSanPhamId")
                        .HasColumnType("bigint");

                    b.Property<long>("lvdLoai_San_PhamlvdId")
                        .HasColumnType("bigint");

                    b.Property<string>("lvdMaSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("lvdSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("lvdTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lvdId");

                    b.HasIndex("lvdLoai_San_PhamlvdId");

                    b.ToTable("LvdSan_Pham");
                });

            modelBuilder.Entity("LVDDay9.Models.LvdSan_Pham", b =>
                {
                    b.HasOne("LVDDay9.Models.LvdLoai_San_Pham", "lvdLoai_San_Pham")
                        .WithMany("lvdSan_Phams")
                        .HasForeignKey("lvdLoai_San_PhamlvdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lvdLoai_San_Pham");
                });

            modelBuilder.Entity("LVDDay9.Models.LvdLoai_San_Pham", b =>
                {
                    b.Navigation("lvdSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
